### PR TITLE
coverage: stop assuming uniform coverage

### PR DESCRIPTION
**Pull request by jeffkaufman**
Instead, assume non-uniform coverage estimated from SARS-CoV-2 in MU data.  This primarily shows up as substantially worse tail outcomes.

See https://docs.google.com/document/d/1f2G2A1uXgCTVleCp7kRxB7W9zRsdxrVAa-qcPns8HBU/edit and https://docs.google.com/document/d/1rjcomd2xmSDEkuQzM1xD3lXlxWm7SGGTuJ-pGZMfWMY/edit

### CODE REVIEW

**Review by dp-rice — COMMENTED** [review]
I haven't had time to read this carefully, but I'm having a hard time understanding what it's doing. In particular, what exactly do the elements of `html/coverage-distribution.js` represent?

**Comment by jeffkaufman** [comment]
The elements in the file represent the (sorted) base-by-base fraction of sequencing reads covering each base in SARS-CoV-2.  By picking a random element from the file we are doing something close to sampling from the distribution that generated our observed coverage.

**Comment by dp-rice** [comment]
I still don't understand what the pairs of numbers are in the file.

**Comment by jeffkaufman** [comment]
@dp-rice 
> I still don't understand what the pairs of numbers are in the file.

Sorry!  I should have looked again at the file before answering your question, because there's an additional transformation on it.

The process for generating it was:

1. For each location along the SARS-CoV-2 genome, observe the fraction of sequencing reads hitting anywhere on the genome that hit that location
2. Round these coverage fractions to four decimal places
3. Count how many locations had a given coverage fraction

So `"0.0037": 322,` means that 322 of the bases in SARS-CoV-2 were observed in at least 0.365% but fewer than 0.375% of sequencing reads that observed SARS-CoV-2.

**Review by dp-rice — APPROVED** [review]
LGTM. Reviewed on call.

**Pull request merged**
